/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.ConfigureASystem;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.OverlayLayout;
import javax.swing.border.Border;

/**
 *
 * @author shawson
 */
public class SignIn extends javax.swing.JFrame {
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    /**
     * Creates new form SignUp
     */
    public SignIn() {
        initComponents();        
        this.dispose();
        this.setUndecorated(true);
        this.setSize(1300, 697);        
        this.setLocationRelativeTo(null);       
        transparencyJPanel.setBackground(new Color(0, 0, 0, 150));
        container.setVisible(false);
//        system = dB4OUtil.retrieveSystem();
        this.system = ConfigureASystem.configure(); 
        container.setSize(1300, 697);
        this.setSize(1300, 697);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentJPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        signinJButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        transparencyJPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 697));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentJPanel.setPreferredSize(new java.awt.Dimension(1300, 697));
        contentJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginJPanel.setBackground(new java.awt.Color(102, 102, 102));
        loginJPanel.setPreferredSize(new java.awt.Dimension(490, 697));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Noteworthy", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER NAME");

        userNameJTextField.setBackground(new java.awt.Color(102, 102, 102));
        userNameJTextField.setBorder(null);

        passwordField.setBackground(new java.awt.Color(102, 102, 102));
        passwordField.setBorder(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Oriya MN", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");

        jLabel7.setFont(new java.awt.Font("Luminari", 2, 13)); // NOI18N
        jLabel7.setText("Fast sign in with other social media");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-facebook.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-google.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-weixin.png"))); // NOI18N
        jLabel10.setText("jLabel9");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-twitter.png"))); // NOI18N
        jLabel11.setText("jLabel9");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signinJButton.setBackground(new java.awt.Color(102, 102, 102));
        signinJButton.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        signinJButton.setText("Sign in");
        signinJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signinJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signinJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinJButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinJButtonMouseEntered(evt);
            }
        });
        signinJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinJButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Luminari", 2, 13)); // NOI18N
        jLabel12.setText("Do not have an account? ");

        signUpLabel.setBackground(new java.awt.Color(102, 102, 102));
        signUpLabel.setFont(new java.awt.Font("Luminari", 2, 13)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(102, 255, 255));
        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLabel.setText("Sign up");
        signUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpLabelMouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user.png"))); // NOI18N
        jLabel13.setText("jLabel8");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-password.png"))); // NOI18N
        jLabel14.setText("jLabel8");

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addGap(100, 100, 100))
                    .addGroup(loginJPanelLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(signUpLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(loginJPanelLayout.createSequentialGroup()
                        .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNameJTextField)
                                .addComponent(jSeparator1)
                                .addComponent(passwordField)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(signinJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(signinJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(signUpLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(79, 79, 79))
        );

        jLayeredPane1.add(loginJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 650, 700));

        container.setPreferredSize(new java.awt.Dimension(1300, 700));
        container.setLayout(new java.awt.CardLayout());
        jLayeredPane1.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        transparencyJPanel.setPreferredSize(new java.awt.Dimension(379, 697));
        transparencyJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("PilGi", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vaccine System");
        transparencyJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, 55));

        jLabel2.setFont(new java.awt.Font("PilGi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Best of the Best");
        transparencyJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 380, 54));

        jLayeredPane1.add(transparencyJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 700));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/covid19dose.jpg"))); // NOI18N
        jLayeredPane1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 700));

        contentJPanel.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(contentJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void signinJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinJButtonActionPerformed
//         Get user name
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;

        if(userAccount == null) {
            //Step 2: Go inside each network and check each enterprise
            for(Network network : system.getNetworkList()){
                //Step 2.a: check against each enterprise
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                    //Step 3:check against each organization for each enterprise
                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        //                        organization.getUserAccountDirectory().getUserAccountList().forEach(System.out::println);
                        userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                        if(userAccount != null){
                            inNetwork = network;
                            inEnterprise = enterprise;
                            inOrganization = organization;
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }

            if(userAccount == null){
                JOptionPane.showMessageDialog(null, "Invalid Username / Password", "Login Error", 2);
                return;
            }
//            System.out.println("The role of current user account:");
//            System.out.println(userAccount.getRole());
//            CardLayout layout=(CardLayout)loginJPanel.getLayout();
//            loginJPanel.add("workArea",userAccount.getRole().createWorkArea(loginJPanel, userAccount, inOrganization, inEnterprise, system));
//            layout.next(loginJPanel);
//            SecondBox second = new SecondBox(); 
//            second.setVisible(true);
//            second.pack();
//            second.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            second.setLocationRelativeTo(null);
//            this.dispose();
            System.out.println(inNetwork);
            CardLayout layout = (CardLayout)container.getLayout();            
            container.add("workArea",userAccount.getRole().createWorkArea(container, this, userAccount, inOrganization, inEnterprise, inNetwork, system));
            layout.next(container);
           
        }

        else{
//            System.out.println("The role of current user account:");
//            System.out.println(userAccount.getRole());
//            CardLayout layout=(CardLayout)loginJPanel.getLayout();
//            loginJPanel.add("workArea",userAccount.getRole().createWorkArea(loginJPanel, userAccount, inOrganization, inEnterprise, system));
//            layout.next(loginJPanel);
           
            System.out.println(inNetwork);
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("workArea",userAccount.getRole().createWorkArea(container, this, userAccount, inOrganization, inEnterprise, inNetwork, system));
            layout.next(container);           
        }
        container.setVisible(true);        
        loginJPanel.setVisible(false);
        transparencyJPanel.setVisible(false);
        backgroundLabel.setVisible(false);
//        signinJButton.setEnabled(false);
//        signoutJButton.setEnabled(true);
//        userNameJTextField.setEnabled(false);
//        passwordField.setEnabled(false);
    }//GEN-LAST:event_signinJButtonActionPerformed
    
    public void setJFrameVisible() {
        loginJPanel.setVisible(true);
        transparencyJPanel.setVisible(true);
        backgroundLabel.setVisible(true);
        container.setVisible(false);
        this.revalidate();
        this.repaint();
    }
    
    public DB4OUtil getB4OUtil() {
        return this.dB4OUtil;
    }
    
    
    private void signUpLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseEntered
        Border labelBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        signUpLabel.setBorder(labelBorder);
    }//GEN-LAST:event_signUpLabelMouseEntered

    private void signUpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseExited
        signUpLabel.setBorder(null);
    }//GEN-LAST:event_signUpLabelMouseExited

    private void signinJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinJButtonMouseEntered
        Border btnBorder = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE);
        signinJButton.setBorder(btnBorder);
    }//GEN-LAST:event_signinJButtonMouseEntered

    private void signinJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinJButtonMouseExited
        Border btnBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        signinJButton.setBorder(btnBorder);
    }//GEN-LAST:event_signinJButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignIn frame = new SignIn();
                frame.dispose();
                frame.setUndecorated(true);
                frame.setSize(1300, 697);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel container;
    private javax.swing.JPanel contentJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JButton signinJButton;
    private javax.swing.JPanel transparencyJPanel;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
