/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Signup;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FactoryOrganization;
import Business.Organization.*;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.MainJFrame;
import userinterface.SystemAdminWorkArea.ManageOrganizationJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Jasmine
 */
public class SignupJPanel extends javax.swing.JPanel {
   private JPanel userProcessContainer;
   private EcoSystem system;
   private Network selectedNetwork;
   private Enterprise selectedEnterprise;
   private Organization selectedOrganization;
    /**
     * Creates new form SignupJPanel
     */
    public SignupJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkComboBox = new javax.swing.JComboBox<>();
        enterpriseComboBox = new javax.swing.JComboBox<>();
        OrganizationComboBox = new javax.swing.JComboBox<>();
        roleComboBox = new javax.swing.JComboBox<>();
        submitButon = new javax.swing.JButton();
        btnButtion = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userNameJLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        userNameJLabel1 = new javax.swing.JLabel();
        userNameJLabel2 = new javax.swing.JLabel();
        userNameJLabel3 = new javax.swing.JLabel();
        userNameJLabel4 = new javax.swing.JLabel();
        userNameJLabel5 = new javax.swing.JLabel();

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        OrganizationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitButon.setText("Submit");
        submitButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButonActionPerformed(evt);
            }
        });

        btnButtion.setText("Back");
        btnButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtionActionPerformed(evt);
            }
        });

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("password");

        userNameJLabel.setText("UserName");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        userNameJLabel1.setText("Network");

        userNameJLabel2.setText("Enterprise");

        userNameJLabel3.setText("Organization");

        userNameJLabel4.setText("Role");

        userNameJLabel5.setText("SignUp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(userNameJLabel))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnButtion)
                                    .addComponent(userNameJLabel2)
                                    .addComponent(userNameJLabel3)
                                    .addComponent(userNameJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userNameJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(userNameJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(OrganizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(submitButon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButtion)
                    .addComponent(userNameJLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrganizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtionActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnButtionActionPerformed

    private void submitButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButonActionPerformed
        // TODO add your handling code here:
        Employee employee = new Employee("test", 123, "6523213123");
        system.getEmployeeDirectory().getEmployeeList().add(employee);
//        UserAccount ua = system.getUserAccountDirectory().createUserAccount("s", "s", employee, new SystemAdminRole());
        Role role =(Role) roleComboBox.getSelectedItem() ;
        String inputUserName = userNameField.getText();
        String inputPassWord = passwordField.getText();
        String inputPassword = String.valueOf(inputPassWord);   
        UserAccount ua = system.getUserAccountDirectory().authenticateUser(inputUserName, inputPassword);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        if (ua == null) {
            submitButon.setEnabled(true);
            userNameField.setEnabled(false);
            passwordField.setEnabled(false);
            submitButon.setEnabled(false);
            userNameField.setText("");
            passwordField.setText("");
            networkComboBox.setEnabled(false);
            enterpriseComboBox.setEnabled(false);
            OrganizationComboBox.setEnabled(false);
            roleComboBox.setEnabled(false);
            UserAccount u = system.getUserAccountDirectory().createUserAccount(inputUserName, inputPassword, employee, role);
            JOptionPane.showMessageDialog(null, "Account created successfully  ");
        }
        else {
            JOptionPane.showMessageDialog(null, "Duplicate password/username, enter again ");
        }
    }//GEN-LAST:event_submitButonActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> OrganizationComboBox;
    private javax.swing.JButton btnButtion;
    private javax.swing.JComboBox<Object> enterpriseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<Object> networkComboBox;
    private javax.swing.JTextField passwordField;
    private javax.swing.JComboBox<Object> roleComboBox;
    private javax.swing.JButton submitButon;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameJLabel;
    private javax.swing.JLabel userNameJLabel1;
    private javax.swing.JLabel userNameJLabel2;
    private javax.swing.JLabel userNameJLabel3;
    private javax.swing.JLabel userNameJLabel4;
    private javax.swing.JLabel userNameJLabel5;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
        OrganizationComboBox.removeAllItems();
        enterpriseComboBox.removeAllItems();
        networkComboBox.removeAllItems();
        roleComboBox.removeAllItems();
        system.getNetworkList().forEach((network) -> {
            networkComboBox.addItem(network);
       });


        selectedNetwork = (Network) networkComboBox.getSelectedItem();
        for (Enterprise enterprise : selectedNetwork.getEnterpriseDirectory().getEnterpriseList()) {            
                enterpriseComboBox.addItem(enterprise);
        }  
        networkComboBox.addActionListener((e) -> {
            enterpriseComboBox.removeAllItems();
            for (Enterprise enterprise : selectedNetwork.getEnterpriseDirectory().getEnterpriseList()) {            
                enterpriseComboBox.addItem(enterprise);
            }
        });
        
        
        selectedEnterprise = (Enterprise) enterpriseComboBox.getSelectedItem();

        for (Organization.OrganizationType o : selectedEnterprise.getSupportedOrganizations()) {
            OrganizationComboBox.addItem(o);
        }        
        enterpriseComboBox.addActionListener((e) -> {
            Enterprise selectedEnterprise = (Enterprise) enterpriseComboBox.getSelectedItem();
            OrganizationComboBox.removeAllItems();
            if (selectedEnterprise == null) {
                OrganizationComboBox.addItem("");
            } 
            else {                
//                System.out.println(selectedEnterprise);
//                System.out.println(selectedEnterprise.getSupportedOrganizations().isEmpty());
                for (Organization.OrganizationType o : selectedEnterprise.getSupportedOrganizations()) {
                    OrganizationComboBox.addItem(o);
                }
            }
        });
        Organization.OrganizationType type = (Organization.OrganizationType)OrganizationComboBox.getSelectedItem();
        Organization organization;
        if (type.getValue().equals(Organization.OrganizationType.Factory.getValue())){
            organization = new FactoryOrganization();
          
        }
        else if (type.getValue().equals(Organization.OrganizationType.Warehouse.getValue())){
            organization = new WarehouseOrganization();
          
        }
        else if (type.getValue().equals(Organization.OrganizationType.DoPH.getValue())){
            organization = new DoPHOrganization();
            
        }
        else if (type.getValue().equals(Organization.OrganizationType.Doctor.getValue())){
            organization = new DoctorOrganization();
           
        } else {
            organization = new HealthDepartmentOrganization();
           
        }        

        for (Role o: organization.getSupportedRole()) {
            roleComboBox.addItem(o);
        } 
        OrganizationComboBox.addActionListener((e) -> {
        roleComboBox.removeAllItems();
        Organization finalOrganization;
        Organization.OrganizationType finalType = (Organization.OrganizationType)OrganizationComboBox.getSelectedItem();
        if (finalType == null) {
            }else{ 
        if (finalType.getValue().equals(Organization.OrganizationType.Factory.getValue())){
            finalOrganization = new FactoryOrganization();
            System.out.println("Factory");
            for (Role o : finalOrganization.getSupportedRole()) {
                    roleComboBox.addItem(o);
                    System.out.println(o.getClass().getName());}
          
        }
        else if (finalType.getValue().equals(Organization.OrganizationType.Warehouse.getValue())){
            finalOrganization = new WarehouseOrganization();
            System.out.println("Warehouse");
             for (Role o : finalOrganization.getSupportedRole()) {
                    roleComboBox.addItem(o);
                    System.out.println(o.getClass().getName());}
          
        }
        else if (finalType.getValue().equals(Organization.OrganizationType.HealthDepartment.getValue())){
            finalOrganization = new DoPHOrganization();
            System.out.println("HealthDepartment");
             for (Role o : finalOrganization.getSupportedRole()) {
                    roleComboBox.addItem(o);
                    System.out.println(o.getClass().getName());}
            
        }
        else if (finalType.getValue().equals(Organization.OrganizationType.Doctor.getValue())){
            finalOrganization = new DoctorOrganization();
            System.out.println("Doctor");
             for (Role o : finalOrganization.getSupportedRole()) {
                    roleComboBox.addItem(o);
                    System.out.println(o.getClass().getName());}
           
       
        //roleComboBox.removeAll();
       
        }}       
                 
        });

        
        
 //       throw new UnsupportedOperationException("Signup ComboBox issue"); //To change body of generated methods, choose Tools | Templates.
    }
}
